sudo: required
services:
  - docker
before_install:
  
  - 'gem install bundler'
  
  - docker build -t app/sample-app -f Dockerfile .

script:
  - 'gem install bundler'
  - 'rake spec'
  - docker run app/sample-app npm run test -- --coverage
