sudo: required
services:
  - docker
before_install:
  
  - sudo gem install bundler -v '< 2'
  - docker build -t app/sample-app -f Dockerfile .

script:
  - docker run app/sample-app npm run test -- --coverage
