sudo: required
services:
  - docker
before_install:
  - gem update --system
  - sudo gem install bundler
  - docker build -t app/sample-app -f Dockerfile.dev .

script:
  - docker run app/sample-app npm run test -- --coverage
